#!/bin/bash
killall -9 nc
killall -9 nc
killall -9 nc

nc -l 8001 -k -q 1 | sudo nice --5 ./rabbit  -window 800x600 -noframe -position 1366x0  | nc  -l 8000 -k -q 1&
./controll -slowwork -window 800x500
#nc 127.0.0.1 8000 -q 1 | sudo nice --5 ./rabbit -preparefade  -window 1366x768 -noframe -position 0x0  | nc  -l 8001 -k -q 1| ./controll -slowwork -window 1366x768 -position 0x0 -noframe -sleep 1 
killall -9 nc
killall -9 nc
killall -9 nc



